### ISSUE TITLE
Invalid checksum

### ISSUE THREAD

**Issue by gajakosh** [anandsiddharth/laravel-paytm-wallet#65]
I am getting this error from your package

[2021-03-04 15:20:05] local.ERROR: Invalid checksum {"exception":"[object] (Exception(code: 0): Invalid checksum at /var/www/html/kookuadmin-dev/vendor/anandsiddharth/laravel-paytm-wallet/src/Providers/PaytmWalletProvider.php:51)
[stacktrace]
#0 /var/www/html/kookuadmin-dev/app/Http/Controllers/PaytmController.php(45): Anand\\LaravelPaytmWallet\\Providers\\PaytmWalletProvider->response()
#1 /var/www/html/kookuadmin-dev/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\PaytmController->paymentCallback()
#2 /var/www/html/kookuadmin-dev/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('paymentCallback', Array)
#3 /var/www/html/kookuadmin-dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\PaytmController), 'paymentCallback')
#4 /var/www/html/kookuadmin-dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\\Routing\\Route->runController()
#5 /var/www/html/kookuadmin-dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run()
#6 /var/www/html/kookuadmin-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#7 /var/www/html/kookuadmin-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#8 /var/www/html/kookuadmin-dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#9 /var/www/html/kookuadmin-dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#10 /var/www/html/kookuadmin-dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#11 /var/www/html/kookuadmin-dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#12 /var/www/html/kookuadmin-dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#13 /var/www/html/kookuadmin-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#14 /var/www/html/kookuadmin-dev/app/Http/Middleware/CORS.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 /var/www/html/kookuadmin-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\CORS->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 /var/www/html/kookuadmin-dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /var/www/html/kookuadmin-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /var/www/html/kookuadmin-dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /var/www/html/kookuadmin-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /var/www/html/kookuadmin-dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /var/www/html/kookuadmin-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /var/www/html/kookuadmin-dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /var/www/html/kookuadmin-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /var/www/html/kookuadmin-dev/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /var/www/html/kookuadmin-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /var/www/html/kookuadmin-dev/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/www/html/kookuadmin-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /var/www/html/kookuadmin-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /var/www/html/kookuadmin-dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#30 /var/www/html/kookuadmin-dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#31 /var/www/html/kookuadmin-dev/public/index.php(54): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#32 {main}
"} 

please help asap, it's argent
![inCheck](https://user-images.githubusercontent.com/74967351/109987370-92ceee00-7d2c-11eb-9a46-d063f9521d7f.png)

**Comment by a-ssassi-n** [comment]
Facing the same issue.
Any solution yet?

**Comment by noxidsoft** [comment]
https://www.tutsmake.com/laravel-5-7-paytm-payment-gateway-integration-example/

**Comment by piyushmanolkar** [comment]
Please check types of your fields in $payment->prepare(), I had the same problem, Had to match the type with the types in documentation - https://business.paytm.com/docs/api/initiate-transaction-api/?ref=payments, For example I was passing amount as int, it has to be float.

**Comment by vanshaj1** [comment]
I was facing same error then i did dd($transaction) at the callback function then i found that i was sending **half merchant key**  to Paytm for validation .
There at the callback I was sending half merchant key It was happening because in the env file i wrote **my merchant key without any quotes** . Basically normally it is not needed to do use double quote but if **you check in your merchant key you will get that # is there in your merchant key** ( **# is used for single line comment in php**) so env is getting half of the merchant key as the comment so if you use double quotes there then you error will get resolved . In my case error was only because of  this  . Hope this will help

**Comment by piyushmanolkar** [comment]
> I was facing same error then i did dd($transaction) at the callback function then i found that i was sending **half merchant key** to Paytm for validation . There at the callback I was sending half merchant key It was happening because in the env file i wrote **my merchant key without any quotes** . Basically normally it is not needed to do use double quote but if **you check in your merchant key you will get that # is there in your merchant key** ( **# is used for single line comment in php**) so env is getting half of the merchant key as the comment so if you use double quotes there then you error will get resolved . In my case error was only because of this . Hope this will help

Are you able to make test payments after putting the key in double quotes? I have wasted a whole month on trying to make this package work and then shifted away from Paytm altogether, If you are I'll consider using this package again.

**Comment by vanshaj1** [comment]
Yes I tested it with the test keys provided by paytm and it works fine.By using double quotes in "" in .env file
